name: dev-npm-publish

on:
  push:
    branches:
      - 'main'

jobs:
  dev-npm-publish:
    name: dev-npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Resolve version
        id: version
        run: echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Version based on commit: 0.0.0-dev.${{ steps.vars.outputs.sha_short }}"
        run: npm version 0.0.0-dev.${{ steps.version.outputs.GIT_SHA_SHORT }} --force --no-git-tag-version

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build

      # - name: Fork
      #   run: yarn run ganache:fork &
      #   env:
      #     PUBLIC_ADDRESS: ${{ secrets.PUBLIC_ADDRESS }}
      #     ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}

      # - name: Test
      #   run: yarn run test
      #   env:
      #     MAINNET_ETHERSCAN_API_KEY: ${{ secrets.MAINNET_ETHERSCAN_API_KEY }}
      #     POLYGON_ETHERSCAN_API_KEY: ${{ secrets.POLYGON_ETHERSCAN_API_KEY }}

      - name: Publish Dev Release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: dev
          access: public



